# Generated by Django 5.2.1 on 2025-07-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlquilerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('dias_a_cobrar', models.PositiveIntegerField(blank=True, null=True)),
                ('precio_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal_item', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento individual en % (ej. 10 para 10%)', max_digits=10)),
                ('valor_item', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EventoAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estado', 'Cambio de estado'), ('abono', 'Abono registrado'), ('salida', 'Entrega de productos'), ('devolucion', 'Devolución'), ('nota', 'Nota interna')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_asociado', models.CharField(blank=True, max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total cobro del alquiler', max_digits=10)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_curso', 'En curso'), ('con_abono', 'Con abono'), ('liquidado', 'Liquidado'), ('anulado', 'Anulado')], default='borrador', max_length=20)),
                ('descuento_general', models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento general en % sobre el total del alquiler', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alquileres', to='cliente.cliente')),
            ],
        ),
    ]
