# Generated by Django 5.2.1 on 2025-07-05 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alquiler', '0001_initial'),
        ('producto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alquileres_creados_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alquileres_actualizados_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alquileritem',
            name='alquiler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='alquiler.alquiler'),
        ),
        migrations.AddField(
            model_name='alquileritem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto'),
        ),
        migrations.AddField(
            model_name='eventoalquiler',
            name='alquiler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='alquiler.alquiler'),
        ),
        migrations.AddField(
            model_name='eventoalquiler',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
