# Generated by Django 5.1.4 on 2025-05-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
