# Generated by Django 5.1.4 on 2025-05-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alter_persona_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='documento',
        ),
    ]
