# Generated by Django 5.2.1 on 2025-07-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('oferta', 'Oferta'), ('convenio', 'Convenio')], max_length=20)),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Ej. 10 para 10%', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('modificado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='empresa.empresa')),
            ],
        ),
    ]
